---
version: "2.1"
services:
        jellyfin:
                build: .
                container_name: genpass
                ports:
                        - 5000:5000
                restart: unless-stopped